name: slidy_carrinho_de_compras
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  get: ^1.15.2

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^3.2.2+1
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  dio: ^4.0.0

dev_dependencies:
  flutter_modular_test: ^1.0.1
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  build_runner: ^1.7.2


flutter:
  uses-material-design: true

scripts:
  mobb: flutter pub get & flutter pub run build_runner build --delete-conflicting-outputs
  mobx: flutter pub get & flutter pub run build_runner watch --delete-conflicting-outputs